import os

MIN_MINUTES = 90
SETTINGS_FILE = os.path.expanduser('~/InStatAnalyst_settings.pkl')
SELECTED_METRICS_FILE = os.path.expanduser('~/InStatAnalyst_selected_metrics.pkl')
MATCH_SELECTED_METRICS_FILE = os.path.expanduser('~/InStatAnalyst_match_selected_metrics.pkl')
MATCH_SETTINGS_FILE = os.path.expanduser('~/InStatAnalyst_match_settings.pkl')

ALL_POSSIBLE_METRICS = [
    'goals_p90', 'assists_p90', 'shots_p90', 'shots_on_target_p90',
    'goals_by_head_p90', 'free_kick_shots_p90', 'free_kick_goals_p90',
    'shots_from_penalty_area_p90', 'shots_on_target_penalty_area_p90',
    'shots_outside_penalty_area_p90', 'shots_on_target_outside_penalty_area_p90',
    'headers_p90', 'headers_on_target_p90',
    'xG_p90',
    'key_passes_p90', 'passes_p90', 'pass_accuracy',
    'short_passes_p90', 'short_passes_accuracy',
    'long_passes_p90', 'long_passes_accuracy',
    'progressive_passes_p90', 'progressive_passes_accuracy',
    'passes_final_third_p90', 'passes_final_third_accuracy',
    'passes_into_penalty_box_p90', 'passes_into_penalty_box_accuracy',
    'super_long_passes_p90', 'super_long_passes_accuracy',
    'crosses_p90', 'crosses_accuracy',
    'passes_for_shot_p90',
    'dribbles_p90', 'dribbles_success_pct',
    'dribbling_final_third_p90', 'dribbling_final_third_success_pct',
    'carry_p90',
    'challenges_p90', 'challenges_won_pct',
    'defensive_challenges_p90', 'defensive_challenges_won_pct',
    'attacking_challenges_p90', 'attacking_challenges_won_pct',
    'air_challenges_p90', 'air_challenges_won_pct',
    'tackles_p90', 'tackles_success_pct',
    'interceptions_p90',
    'loose_ball_recoveries_p90',
    'actions_opp_box_p90', 'actions_opp_box_success_p90',
    'chances_p90', 'chances_successful_p90',
    'chances_created_p90',
    'involvement_scoring_p90',
    'shots_on_target_pct',
    'lost_balls_p90', 'lost_balls_own_half_p90', 'individual_ball_losses_p90',
    'lost_balls_after_passes_p90',
    'challenges_unsuccessful_p90', 'dribbles_unsuccessful_p90',
    'bad_ball_control_p90', 'offsides_p90',
    'mistakes_goals_p90', 'mistakes_chances_p90',
    'fouls_p90', 'fouls_suffered_p90',
    'yellow_cards_p90', 'red_cards_p90',
    'ball_recoveries_p90', 'ball_recoveries_opp_half_p90',
    'actions_successful_p90', 'actions_unsuccessful_p90',
    'final_third_entries_p90', 'final_third_carry_p90',
    'final_third_entries_pass_p90',
    'open_passes_received_p90',
    'long_open_passes_received_p90',
    'super_long_open_passes_received_p90',
    'open_passes_received_first_third_p90',
    'open_passes_received_central_third_p90',
    'open_passes_received_final_third_p90',
    'open_passes_received_opponent_box_p90',
    'ttd_actions_p90', 'ttd_opp_actions_p90'
]

NEGATIVE_METRICS = [
    'lost_balls_p90', 'lost_balls_own_half_p90', 'individual_ball_losses_p90',
    'lost_balls_after_passes_p90', 'challenges_unsuccessful_p90',
    'dribbles_unsuccessful_p90', 'bad_ball_control_p90', 'offsides_p90',
    'yellow_cards_p90', 'red_cards_p90', 'mistakes_goals_p90', 'mistakes_chances_p90',
    'fouls_p90', 'actions_unsuccessful_p90',
    'lost_balls', 'lost_balls_own_half', 'individual_ball_losses',
    'lost_balls_after_passes', 'challenges_unsuccessful',
    'dribbles_unsuccessful', 'bad_ball_control', 'offsides',
    'yellow_cards', 'red_cards', 'mistakes_goals', 'mistakes_chances',
    'fouls', 'actions_unsuccessful',
]

DEFAULT_METRICS_WEIGHTS = {
    'FW': {
        'goals_p90': 3.0, 'xG_p90': 2.5, 'shots_on_target_p90': 2.0,
        'assists_p90': 1.5, 'dribbles_p90': 1.2, 'actions_opp_box_p90': 1.2,
        'chances_successful_p90': 1.0, 'key_passes_p90': 1.0, 'pass_accuracy': 0.5,
        'lost_balls_p90': -2.0, 'individual_ball_losses_p90': -1.5,
        'yellow_cards_p90': -0.5, 'red_cards_p90': -3.0, 'mistakes_goals_p90': -2.5,
        'mistakes_chances_p90': -1.0, 'fouls_p90': -0.5,
        'ttd_actions_p90': 1.0, 'ttd_opp_actions_p90': 1.0,
    },
    'AM': {
        'key_passes_p90': 3.0, 'assists_p90': 2.5, 'progressive_passes_p90': 2.0,
        'pass_accuracy': 1.5, 'dribbles_p90': 1.5, 'goals_p90': 1.0,
        'xG_p90': 1.0, 'shots_on_target_p90': 1.0, 'chances_p90': 1.0,
        'lost_balls_p90': -1.5, 'individual_ball_losses_p90': -1.0,
        'yellow_cards_p90': -0.5, 'red_cards_p90': -3.0, 'mistakes_goals_p90': -1.5,
        'mistakes_chances_p90': -1.0, 'fouls_p90': -0.5,
        'ttd_actions_p90': 1.0, 'ttd_opp_actions_p90': 1.0,
    },
    'CM': {
        'pass_accuracy': 3.0, 'progressive_passes_p90': 2.5, 'interceptions_p90': 2.0,
        'tackles_p90': 1.5, 'key_passes_p90': 1.5, 'progressive_passes_accuracy': 1.5,
        'challenges_won_pct': 1.0, 'ball_recoveries_p90': 1.0,
        'lost_balls_own_half_p90': -2.0, 'lost_balls_p90': -1.5,
        'individual_ball_losses_p90': -1.0, 'yellow_cards_p90': -1.0,
        'red_cards_p90': -3.0, 'mistakes_goals_p90': -2.0, 'mistakes_chances_p90': -1.5,
        'fouls_p90': -0.5,
        'ttd_actions_p90': 1.0, 'ttd_opp_actions_p90': 1.0,
    },
    'FB': {
        'tackles_p90': 2.5, 'interceptions_p90': 2.0, 'crosses_accuracy': 2.0,
        'pass_accuracy': 1.5, 'tackles_success_pct': 1.5, 'dribbles_p90': 1.2,
        'key_passes_p90': 1.2, 'progressive_passes_p90': 1.0,
        'mistakes_goals_p90': -2.5, 'mistakes_chances_p90': -1.5,
        'lost_balls_own_half_p90': -2.0, 'lost_balls_p90': -1.0,
        'yellow_cards_p90': -1.0, 'red_cards_p90': -3.0, 'fouls_p90': -0.5,
        'ttd_actions_p90': 1.0, 'ttd_opp_actions_p90': 1.0,
    },
    'CB': {
        'interceptions_p90': 3.0, 'tackles_p90': 2.5, 'air_challenges_won_pct': 2.5,
        'tackles_success_pct': 2.0, 'challenges_won_pct': 1.5, 'ball_recoveries_p90': 1.5,
        'loose_ball_recoveries_p90': 1.5, 'pass_accuracy': 1.0,
        'mistakes_goals_p90': -3.0, 'mistakes_chances_p90': -2.0,
        'lost_balls_own_half_p90': -2.5, 'individual_ball_losses_p90': -1.5,
        'yellow_cards_p90': -1.0, 'red_cards_p90': -3.5, 'fouls_p90': -1.0,
        'ttd_actions_p90': 1.0, 'ttd_opp_actions_p90': 1.0,
    },
}
for pos in DEFAULT_METRICS_WEIGHTS:
    for m in ALL_POSSIBLE_METRICS:
        if m not in DEFAULT_METRICS_WEIGHTS[pos]:
            DEFAULT_METRICS_WEIGHTS[pos][m] = 0.0

METRIC_NAMES_RU = {
    'goals_p90': 'Голы', 'assists_p90': 'Голевые передачи',
    'shots_p90': 'Удары', 'shots_on_target_p90': 'Удары в створ',
    'goals_by_head_p90': 'Голы головой',
    'free_kick_shots_p90': 'Штрафные удары', 'free_kick_goals_p90': 'Голы со штрафных',
    'shots_from_penalty_area_p90': 'Удары из штрафной',
    'shots_on_target_penalty_area_p90': 'В створ из штрафной',
    'shots_outside_penalty_area_p90': 'Удары из-за штрафной',
    'shots_on_target_outside_penalty_area_p90': 'В створ из-за штрафной',
    'headers_p90': 'Удары головой', 'headers_on_target_p90': 'Удары головой в створ',
    'xG_p90': 'xG (ожидаемые голы)',
    'key_passes_p90': 'Ключевые передачи', 'passes_p90': 'Передачи',
    'pass_accuracy': 'Точность передач %',
    'short_passes_p90': 'Короткие передачи', 'short_passes_accuracy': 'Короткие точные %',
    'long_passes_p90': 'Длинные передачи', 'long_passes_accuracy': 'Длинные точные %',
    'progressive_passes_p90': 'Продвигающие передачи',
    'progressive_passes_accuracy': 'Продвигающие точные %',
    'passes_final_third_p90': 'Передачи в финальную треть',
    'passes_final_third_accuracy': 'В финальную треть точные %',
    'passes_into_penalty_box_p90': 'Передачи в штрафную',
    'passes_into_penalty_box_accuracy': 'В штрафную точные %',
    'super_long_passes_p90': 'Сверхдлинные передачи',
    'super_long_passes_accuracy': 'Сверхдлинные точные %',
    'crosses_p90': 'Кроссы', 'crosses_accuracy': 'Кроссы точные %',
    'passes_for_shot_p90': 'Передачи под удар',
    'dribbles_p90': 'Обводки', 'dribbles_success_pct': 'Обводки успешные %',
    'dribbling_final_third_p90': 'Обводки в финальной трети',
    'dribbling_final_third_success_pct': 'Обводки в финальной трети %',
    'carry_p90': 'Продвижение мяча (Carry)',
    'challenges_p90': 'Единоборства', 'challenges_won_pct': 'Единоборства выигранные %',
    'defensive_challenges_p90': 'Оборонительные единоборства',
    'defensive_challenges_won_pct': 'Оборонительные един. выигранные %',
    'attacking_challenges_p90': 'Атакующие единоборства',
    'attacking_challenges_won_pct': 'Атакующие един. выигранные %',
    'air_challenges_p90': 'Верховые единоборства',
    'air_challenges_won_pct': 'Верховые единоборства %',
    'tackles_p90': 'Отборы', 'tackles_success_pct': 'Отборы успешные %',
    'interceptions_p90': 'Перехваты',
    'loose_ball_recoveries_p90': 'Подборы',
    'actions_opp_box_p90': 'Действия в штрафной соперника',
    'actions_opp_box_success_p90': 'Успешные действия в штрафной',
    'chances_p90': 'Голевые моменты', 'chances_successful_p90': 'Реализованные моменты',
    'chances_created_p90': 'Созданные моменты',
    'involvement_scoring_p90': 'Участие в голевых атаках',
    'shots_on_target_pct': 'Точность ударов %',
    'lost_balls_p90': 'Потери мяча', 'lost_balls_own_half_p90': 'Потери на своей половине',
    'individual_ball_losses_p90': 'Индивидуальные потери',
    'lost_balls_after_passes_p90': 'Потери после передач',
    'challenges_unsuccessful_p90': 'Неудачные единоборства',
    'dribbles_unsuccessful_p90': 'Неудачные обводки',
    'bad_ball_control_p90': 'Плохой приём мяча',
    'offsides_p90': 'Офсайды',
    'mistakes_goals_p90': 'Ошибки → голы', 'mistakes_chances_p90': 'Ошибки → моменты',
    'fouls_p90': 'Фолы', 'fouls_suffered_p90': 'Фолы на игроке',
    'yellow_cards_p90': 'Жёлтые карточки', 'red_cards_p90': 'Красные карточки',
    'ball_recoveries_p90': 'Возвраты мяча',
    'ball_recoveries_opp_half_p90': 'Возвраты на чужой половине',
    'actions_successful_p90': 'Успешные действия',
    'actions_unsuccessful_p90': 'Неуспешные действия',
    'final_third_entries_p90': 'Входы в финальную треть',
    'final_third_carry_p90': 'Входы в финальную треть (дриблинг)',
    'final_third_entries_pass_p90': 'Входы в финальную треть (пас)',
    'open_passes_received_p90': 'Открытые передачи принято',
    'long_open_passes_received_p90': 'Длинные передачи принято',
    'super_long_open_passes_received_p90': 'Сверхдлинные передачи принято',
    'open_passes_received_first_third_p90': 'Принято в 1-й трети',
    'open_passes_received_central_third_p90': 'Принято в центр. трети',
    'open_passes_received_final_third_p90': 'Принято в финальной трети',
    'open_passes_received_opponent_box_p90': 'Принято в штрафной',
    'ttd_actions_p90': 'ТТД/уд',
    'ttd_opp_actions_p90': 'ТТД у чужих ворот/уд',
}

MATCH_ALL_METRICS = [
    'goals', 'assists', 'shots', 'shots_on_target',
    'goals_by_head', 'free_kick_shots', 'free_kick_goals',
    'shots_from_penalty_area', 'shots_on_target_penalty_area',
    'shots_outside_penalty_area', 'shots_on_target_outside_penalty_area',
    'headers', 'headers_on_target', 'xG',
    'key_passes', 'passes', 'pass_accuracy',
    'short_passes', 'short_passes_accuracy', 'long_passes', 'long_passes_accuracy',
    'progressive_passes', 'progressive_passes_accuracy',
    'passes_final_third', 'passes_final_third_accuracy',
    'passes_into_penalty_box', 'passes_into_penalty_box_accuracy',
    'super_long_passes', 'super_long_passes_accuracy',
    'crosses', 'crosses_accuracy', 'passes_for_shot',
    'dribbles', 'dribbles_success_pct',
    'dribbling_final_third', 'dribbling_final_third_success_pct', 'carry',
    'challenges', 'challenges_won_pct',
    'defensive_challenges', 'defensive_challenges_won_pct',
    'attacking_challenges', 'attacking_challenges_won_pct',
    'air_challenges', 'air_challenges_won_pct',
    'tackles', 'tackles_success_pct', 'interceptions',
    'loose_ball_recoveries', 'actions_opp_box', 'actions_opp_box_success',
    'chances', 'chances_successful', 'chances_created',
    'involvement_scoring', 'shots_on_target_pct',
    'lost_balls', 'lost_balls_own_half', 'individual_ball_losses',
    'lost_balls_after_passes', 'challenges_unsuccessful',
    'dribbles_unsuccessful', 'bad_ball_control', 'offsides',
    'mistakes_goals', 'mistakes_chances',
    'fouls', 'fouls_suffered',
    'yellow_cards', 'red_cards',
    'ball_recoveries', 'ball_recoveries_opp_half',
    'actions_successful', 'actions_unsuccessful',
    'final_third_entries', 'final_third_carry', 'final_third_entries_pass',
    'open_passes_received', 'long_open_passes_received',
    'super_long_open_passes_received',
    'open_passes_received_first_third', 'open_passes_received_central_third',
    'open_passes_received_final_third', 'open_passes_received_opponent_box',
]

MATCH_METRIC_NAMES_RU = {
    'goals': 'Голы', 'assists': 'Голевые передачи',
    'shots': 'Удары', 'shots_on_target': 'Удары в створ',
    'goals_by_head': 'Голы головой',
    'free_kick_shots': 'Штрафные удары', 'free_kick_goals': 'Голы со штрафных',
    'shots_from_penalty_area': 'Удары из штрафной',
    'shots_on_target_penalty_area': 'В створ из штрафной',
    'shots_outside_penalty_area': 'Удары из-за штрафной',
    'shots_on_target_outside_penalty_area': 'В створ из-за штрафной',
    'headers': 'Удары головой', 'headers_on_target': 'Удары головой в створ',
    'xG': 'xG (ожидаемые голы)',
    'key_passes': 'Ключевые передачи', 'passes': 'Передачи',
    'pass_accuracy': 'Точность передач',
    'short_passes': 'Короткие передачи', 'short_passes_accuracy': 'Короткие точные',
    'long_passes': 'Длинные передачи', 'long_passes_accuracy': 'Длинные точные',
    'progressive_passes': 'Продвигающие передачи',
    'progressive_passes_accuracy': 'Продвигающие точные',
    'passes_final_third': 'Передачи в финальную треть',
    'passes_final_third_accuracy': 'В финальную треть точные',
    'passes_into_penalty_box': 'Передачи в штрафную',
    'passes_into_penalty_box_accuracy': 'В штрафную точные',
    'super_long_passes': 'Сверхдлинные передачи',
    'super_long_passes_accuracy': 'Сверхдлинные точные',
    'crosses': 'Кроссы', 'crosses_accuracy': 'Кроссы точные',
    'passes_for_shot': 'Передачи под удар',
    'dribbles': 'Обводки', 'dribbles_success_pct': 'Обводки успешные',
    'dribbling_final_third': 'Обводки в финальной трети',
    'dribbling_final_third_success_pct': 'Обводки в финальной трети',
    'carry': 'Продвижение мяча (Carry)',
    'challenges': 'Единоборства', 'challenges_won_pct': 'Единоборства выигранные',
    'defensive_challenges': 'Оборонительные единоборства',
    'defensive_challenges_won_pct': 'Оборонительные един. выигранные',
    'attacking_challenges': 'Атакующие единоборства',
    'attacking_challenges_won_pct': 'Атакующие един. выигранные',
    'air_challenges': 'Верховые единоборства',
    'air_challenges_won_pct': 'Верховые единоборства',
    'tackles': 'Отборы', 'tackles_success_pct': 'Отборы успешные',
    'interceptions': 'Перехваты',
    'loose_ball_recoveries': 'Подборы',
    'actions_opp_box': 'Действия в штрафной соперника',
    'actions_opp_box_success': 'Успешные действия в штрафной',
    'chances': 'Голевые моменты', 'chances_successful': 'Реализованные моменты',
    'chances_created': 'Созданные моменты',
    'involvement_scoring': 'Участие в голевых атаках',
    'shots_on_target_pct': 'Точность ударов',
    'lost_balls': 'Потери мяча', 'lost_balls_own_half': 'Потери на своей половине',
    'individual_ball_losses': 'Индивидуальные потери',
    'lost_balls_after_passes': 'Потери после передач',
    'challenges_unsuccessful': 'Неудачные единоборства',
    'dribbles_unsuccessful': 'Неудачные обводки',
    'bad_ball_control': 'Плохой приём мяча',
    'offsides': 'Офсайды',
    'mistakes_goals': 'Ошибки → голы', 'mistakes_chances': 'Ошибки → моменты',
    'fouls': 'Фолы', 'fouls_suffered': 'Фолы на игроке',
    'yellow_cards': 'Жёлтые карточки', 'red_cards': 'Красные карточки',
    'ball_recoveries': 'Возвраты мяча',
    'ball_recoveries_opp_half': 'Возвраты на чужой половине',
    'actions_successful': 'Успешные действия',
    'actions_unsuccessful': 'Неуспешные действия',
    'final_third_entries': 'Входы в финальную треть',
    'final_third_carry': 'Входы в финальную треть (дриблинг)',
    'final_third_entries_pass': 'Входы в финальную треть (пас)',
    'open_passes_received': 'Открытые передачи принято',
    'long_open_passes_received': 'Длинные передачи принято',
    'super_long_open_passes_received': 'Сверхдлинные передачи принято',
    'open_passes_received_first_third': 'Принято в 1-й трети',
    'open_passes_received_central_third': 'Принято в центр. трети',
    'open_passes_received_final_third': 'Принято в финальной трети',
    'open_passes_received_opponent_box': 'Принято в штрафной',
    'ttd_actions': 'ТТД/уд',
    'ttd_opp_actions': 'ТТД у чужих ворот/уд',
}

DEFAULT_MATCH_WEIGHTS = {
    'FW': {
        'goals': 3.0, 'xG': 2.5, 'shots_on_target': 2.0,
        'assists': 1.5, 'dribbles': 1.2, 'actions_opp_box': 1.2,
        'chances_successful': 1.0, 'key_passes': 1.0, 'pass_accuracy': 0.5,
        'lost_balls': -2.0, 'individual_ball_losses': -1.5,
        'yellow_cards': -0.5, 'red_cards': -3.0, 'mistakes_goals': -2.5,
        'mistakes_chances': -1.0, 'fouls': -0.5,
    },
    'AM': {
        'key_passes': 3.0, 'assists': 2.5, 'progressive_passes': 2.0,
        'pass_accuracy': 1.5, 'dribbles': 1.5, 'goals': 1.0,
        'xG': 1.0, 'shots_on_target': 1.0, 'chances': 1.0,
        'lost_balls': -1.5, 'individual_ball_losses': -1.0,
        'yellow_cards': -0.5, 'red_cards': -3.0, 'mistakes_goals': -1.5,
        'mistakes_chances': -1.0, 'fouls': -0.5,
    },
    'CM': {
        'pass_accuracy': 3.0, 'progressive_passes': 2.5, 'interceptions': 2.0,
        'tackles': 1.5, 'key_passes': 1.5, 'progressive_passes_accuracy': 1.5,
        'challenges_won_pct': 1.0, 'ball_recoveries': 1.0,
        'lost_balls_own_half': -2.0, 'lost_balls': -1.5,
        'individual_ball_losses': -1.0, 'yellow_cards': -1.0,
        'red_cards': -3.0, 'mistakes_goals': -2.0, 'mistakes_chances': -1.5,
        'fouls': -0.5,
    },
    'FB': {
        'tackles': 2.5, 'interceptions': 2.0, 'crosses_accuracy': 2.0,
        'pass_accuracy': 1.5, 'tackles_success_pct': 1.5, 'dribbles': 1.2,
        'key_passes': 1.2, 'progressive_passes': 1.0,
        'mistakes_goals': -2.5, 'mistakes_chances': -1.5,
        'lost_balls_own_half': -2.0, 'lost_balls': -1.0,
        'yellow_cards': -1.0, 'red_cards': -3.0, 'fouls': -0.5,
    },
    'CB': {
        'interceptions': 3.0, 'tackles': 2.5, 'air_challenges_won_pct': 2.5,
        'tackles_success_pct': 2.0, 'challenges_won_pct': 1.5, 'ball_recoveries': 1.5,
        'loose_ball_recoveries': 1.5, 'pass_accuracy': 1.0,
        'mistakes_goals': -3.0, 'mistakes_chances': -2.0,
        'lost_balls_own_half': -2.5, 'individual_ball_losses': -1.5,
        'yellow_cards': -1.0, 'red_cards': -3.5, 'fouls': -1.0,
    },
}
for pos in DEFAULT_MATCH_WEIGHTS:
    for m in MATCH_ALL_METRICS:
        if m not in DEFAULT_MATCH_WEIGHTS[pos]:
            DEFAULT_MATCH_WEIGHTS[pos][m] = 0.0
